#include "OpenFoamExport.hpp"

#include <filesystem>
#include <fstream>
#include <stdexcept>

namespace fs = std::filesystem;

static void writeText(const fs::path& path, const std::string& content) {
    std::ofstream out(path);
    if (!out) throw std::runtime_error("Unable to write " + path.string());
    out << content;
}

void writeOpenFoamCase(const std::string& directory,
                       const PumpParameters& params,
                       const Geometry3DModel& geometry,
                       const FluidDomain& domain,
                       const MeshQualityReport& mesh) {
    const fs::path root(directory);
    fs::create_directories(root / "0");
    fs::create_directories(root / "constant");
    fs::create_directories(root / "system");

    writeText(root / "README.md",
        "# OpenFOAM case scaffold\n\n"
        "Generated from the C++ pump baseline. Add a watertight fluid mesh and patch topology before solving.\n\n"
        "This scaffold is not a completed or validated RANS case.\n");
    writeText(root / "constant" / "transportProperties",
        "FoamFile\n{ version 2.0; format ascii; class dictionary; object transportProperties; }\n\n"
        "nu [0 2 -1 0 0 0 0] " + std::to_string(params.dynamicViscosity / params.fluidDensity) + ";\n");
    writeText(root / "constant" / "turbulenceProperties",
        "FoamFile\n{ version 2.0; format ascii; class dictionary; object turbulenceProperties; }\n\n"
        "simulationType RAS;\nRAS\n{ RASModel kOmegaSST; turbulence on; printCoeffs on; }\n");
    writeText(root / "system" / "controlDict",
        "FoamFile\n{ version 2.0; format ascii; class dictionary; object controlDict; }\n\n"
        "application simpleFoam;\nstartFrom startTime; startTime 0; stopAt endTime; endTime 1000;\n"
        "writeControl timeStep; writeInterval 100;\n");
    writeText(root / "system" / "fvSchemes",
        "FoamFile\n{ version 2.0; format ascii; class dictionary; object fvSchemes; }\n\n"
        "ddtSchemes { default steadyState; }\n"
        "gradSchemes { default cellLimited Gauss linear 1; }\n"
        "divSchemes { default none; div(phi,U) bounded Gauss upwind; div(phi,k) bounded Gauss upwind; div(phi,omega) bounded Gauss upwind; div((nuEff*dev2(T(grad(U))))) Gauss linear; }\n"
        "laplacianSchemes { default Gauss linear corrected; }\n"
        "interpolationSchemes { default linear; }\n"
        "snGradSchemes { default corrected; }\n");
    writeText(root / "system" / "fvSolution",
        "FoamFile\n{ version 2.0; format ascii; class dictionary; object fvSolution; }\n\n"
        "solvers { p { solver GAMG; tolerance 1e-8; relTol 0.05; } U { solver smoothSolver; smoother symGaussSeidel; tolerance 1e-8; relTol 0.05; } '(k|omega)' { solver smoothSolver; smoother symGaussSeidel; tolerance 1e-8; relTol 0.05; } }\n"
        "SIMPLE { nNonOrthogonalCorrectors 1; residualControl { p 1e-5; U 1e-5; '(k|omega)' 1e-5; } }\n"
        "relaxationFactors { fields { p 0.3; } equations { U 0.7; k 0.7; omega 0.7; } }\n");
    writeText(root / "system" / "caseMetadata.json",
        "{\n"
        "  \"case_type\": \"steady_RANS_scaffold\",\n"
        "  \"geometry_watertight_flag\": " + std::string(geometry.watertight ? "true" : "false") + ",\n"
        "  \"fluid_domain_connected_flag\": " + std::string(domain.connected ? "true" : "false") + ",\n"
        "  \"mesh_status\": \"" + mesh.status + "\",\n"
        "  \"patches_expected\": [\"inlet\", \"outlet\", \"rotorWall\", \"statorWall\", \"interface\"],\n"
        "  \"solver_ready\": false,\n"
        "  \"limitation\": \"No 3D volume mesh or boundary patch topology is generated by this exporter.\"\n"
        "}\n");
}
