#include "OpenFoamExport.hpp"

#include <filesystem>
#include <fstream>
#include <stdexcept>

namespace fs = std::filesystem;

static void writeText(const fs::path& path, const std::string& content) {
    std::ofstream out(path);
    if (!out) throw std::runtime_error("Unable to write " + path.string());
    out << content;
}

void writeOpenFoamCase(const std::string& directory,
                       const PumpParameters& params,
                       const Geometry3DModel& geometry,
                       const FluidDomain& domain,
                       const MeshQualityReport& mesh) {
    const fs::path root(directory);
    fs::create_directories(root / "0");
    fs::create_directories(root / "constant");
    fs::create_directories(root / "system");

    writeText(root / "README.md",
        "# OpenFOAM case scaffold\n\n"
        "This is a generated case scaffold. Geometry, volume mesh, and boundary patches must be supplied before solving.\n\n"
        "The scaffold is not a completed or validated RANS case.\n");
    writeText(root / "constant" / "transportProperties",
        "FoamFile\n{ version 2.0; format ascii; class dictionary; object transportProperties; }\n\n"
        "nu [0 2 -1 0 0 0 0] " + std::to_string(params.dynamicViscosity / params.fluidDensity) + ";\n");
    writeText(root / "system" / "controlDict",
        "FoamFile\n{ version 2.0; format ascii; class dictionary; object controlDict; }\n\n"
        "application simpleFoam;\nstartFrom startTime; startTime 0; stopAt endTime; endTime 1000;\n"
        "writeControl timeStep; writeInterval 100;\n");
    writeText(root / "system" / "caseMetadata.json",
        "{\n"
        "  \"case_type\": \"steady_RANS_scaffold\",\n"
        "  \"geometry_watertight_flag\": " + std::string(geometry.watertight ? "true" : "false") + ",\n"
        "  \"fluid_domain_connected_flag\": " + std::string(domain.connected ? "true" : "false") + ",\n"
        "  \"mesh_status\": \"" + mesh.status + "\",\n"
        "  \"solver_ready\": false,\n"
        "  \"limitation\": \"No 3D volume mesh or boundary patch topology is generated by this exporter.\"\n"
        "}\n");
}
